server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=health,info,metrics


# ==============================
# TEST SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[0].id=test-service-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://test-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/test/**


# ==============================
# IDENTITY SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[1].id=identity-service-route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://identity-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/auth/**


# ==============================
# ALLOCATION SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[2].id=allocation-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://allocation-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/allocations/**


# ==============================
# HOSTEL SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[3].id=hostel-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://hostel-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/hostels/**

# ==============================
# COMPLAINT SERVICE
# ==============================
spring.cloud.gateway.server.webmvc.routes[4].id=complaint-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://complaint-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/complaints/**

# ==============================
# LEAVE SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[5].id=leave-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://leave-service
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/leaves/**