spring.application.name=hostel-service

spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000


logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign=DEBUG
logging.level.com.hostelhub.hostelservice.client=DEBUG